# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [1]:
import numpy as np
data2 = np.load("data2.npy")
print(data2)

[[ 1.      1.      1.      1.      1.    ]
 [ 0.     37.4341 35.852   7.02    4.1   ]
 [ 0.     37.6878 37.4016 10.27    4.4   ]
 [ 0.     37.2003 30.4376 78.07    4.    ]
 [ 0.     35.6846 26.7266 42.77    4.5   ]
 [ 0.     36.4171 28.6991 14.86    4.1   ]
 [ 0.     36.0535 31.2135 36.68    5.2   ]
 [ 0.     37.1958 30.6241 50.33    4.8   ]
 [ 0.     36.9653 27.7633  6.93    4.3   ]
 [ 0.     38.893  26.4483 11.62    4.2   ]
 [ 0.     37.3773 36.3855 10.53    4.8   ]
 [ 0.     35.8861 26.0695 28.49    4.9   ]
 [ 0.     37.4635 36.3113 15.29    4.3   ]
 [ 0.     37.0201 36.0845 10.      4.1   ]
 [ 0.     37.6546 26.6698  4.5     4.5   ]
 [ 0.     37.5318 29.848  17.58    4.6   ]
 [ 0.     39.0388 44.1533  7.52    4.5   ]
 [ 0.     38.357  44.8686 10.05    4.1   ]
 [ 0.     35.7018 28.1495  6.25    4.1   ]
 [ 0.     37.6883 37.3968 10.63    4.1   ]
 [ 0.     42.1821 42.5928  5.81    4.    ]]


2. Display the mean and the standard deviation for each column.

In [2]:
print(data2.mean(axis = 1))

[ 1.      16.88122 17.95188 29.94158 21.93624 16.81524 21.8294  24.58998
 15.19172 16.23226 17.81856 19.06912 18.67296 17.44092 14.66488 17.91196
 19.04242 19.47512 14.84026 17.96302 18.91698]


3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [3]:
print(data2 - [1, 25, 25, 10, 4])

[[ 0.00000e+00 -2.40000e+01 -2.40000e+01 -9.00000e+00 -3.00000e+00]
 [-1.00000e+00  1.24341e+01  1.08520e+01 -2.98000e+00  1.00000e-01]
 [-1.00000e+00  1.26878e+01  1.24016e+01  2.70000e-01  4.00000e-01]
 [-1.00000e+00  1.22003e+01  5.43760e+00  6.80700e+01  0.00000e+00]
 [-1.00000e+00  1.06846e+01  1.72660e+00  3.27700e+01  5.00000e-01]
 [-1.00000e+00  1.14171e+01  3.69910e+00  4.86000e+00  1.00000e-01]
 [-1.00000e+00  1.10535e+01  6.21350e+00  2.66800e+01  1.20000e+00]
 [-1.00000e+00  1.21958e+01  5.62410e+00  4.03300e+01  8.00000e-01]
 [-1.00000e+00  1.19653e+01  2.76330e+00 -3.07000e+00  3.00000e-01]
 [-1.00000e+00  1.38930e+01  1.44830e+00  1.62000e+00  2.00000e-01]
 [-1.00000e+00  1.23773e+01  1.13855e+01  5.30000e-01  8.00000e-01]
 [-1.00000e+00  1.08861e+01  1.06950e+00  1.84900e+01  9.00000e-01]
 [-1.00000e+00  1.24635e+01  1.13113e+01  5.29000e+00  3.00000e-01]
 [-1.00000e+00  1.20201e+01  1.10845e+01  0.00000e+00  1.00000e-01]
 [-1.00000e+00  1.26546e+01  1.66980e+00 -5.5000

4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [4]:
print(data2 * 2)

[[  2.       2.       2.       2.       2.    ]
 [  0.      74.8682  71.704   14.04     8.2   ]
 [  0.      75.3756  74.8032  20.54     8.8   ]
 [  0.      74.4006  60.8752 156.14     8.    ]
 [  0.      71.3692  53.4532  85.54     9.    ]
 [  0.      72.8342  57.3982  29.72     8.2   ]
 [  0.      72.107   62.427   73.36    10.4   ]
 [  0.      74.3916  61.2482 100.66     9.6   ]
 [  0.      73.9306  55.5266  13.86     8.6   ]
 [  0.      77.786   52.8966  23.24     8.4   ]
 [  0.      74.7546  72.771   21.06     9.6   ]
 [  0.      71.7722  52.139   56.98     9.8   ]
 [  0.      74.927   72.6226  30.58     8.6   ]
 [  0.      74.0402  72.169   20.       8.2   ]
 [  0.      75.3092  53.3396   9.       9.    ]
 [  0.      75.0636  59.696   35.16     9.2   ]
 [  0.      78.0776  88.3066  15.04     9.    ]
 [  0.      76.714   89.7372  20.1      8.2   ]
 [  0.      71.4036  56.299   12.5      8.2   ]
 [  0.      75.3766  74.7936  21.26     8.2   ]
 [  0.      84.3642  85.1856  11.62     