# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [1]:
import numpy as np
squaremeter_house = [100,63,56,220,130,145,96,81,122,167]
rooms = ["kitchen","living_room","garage","study_room","guest_room","bathroom","parent_room","children_room","garden","sport_room"]
price = [100000,61000,555000,220000,73000,145000,196000,181000,152000,167000]
home = np.array([squaremeter_house,rooms ,price])
print(home)

[['100' '63' '56' '220' '130' '145' '96' '81' '122' '167']
 ['kitchen' 'living_room' 'garage' 'study_room' 'guest_room' 'bathroom'
  'parent_room' 'children_room' 'garden' 'sport_room']
 ['100000' '61000' '555000' '220000' '73000' '145000' '196000' '181000'
  '152000' '167000']]


2. Transpose the array you have created, so that every line can represent features of one house.

In [2]:
home_new = home.T
print(home_new)

[['100' 'kitchen' '100000']
 ['63' 'living_room' '61000']
 ['56' 'garage' '555000']
 ['220' 'study_room' '220000']
 ['130' 'guest_room' '73000']
 ['145' 'bathroom' '145000']
 ['96' 'parent_room' '196000']
 ['81' 'children_room' '181000']
 ['122' 'garden' '152000']
 ['167' 'sport_room' '167000']]


3. Display the shape of the array and explain what it means.

In [3]:
home.shape # array has 3 rows, 10 columns

(3, 10)

4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [4]:
import numpy as np
x = int(input('Enter the size of the x-axis : '))
y = int(input('Enter the size of the y-axis : '))
a = np.ones((x,y))
for m in range (0,x):
    for n in range (0,y):
        if (m%2==1 & n%2==1):
            a[m][n] = 0
print(a)

Enter the size of the x-axis : 6
Enter the size of the y-axis : 5
[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]
